blank_issues_enabled: false
contact_links:
  - name: New feature / UI suggestion
    url: https://github.com/maguid28/Wholphin_fork/discussions/new?category=ideas
    about: Please request new features here
  - name: Questions
    url: https://github.com/maguid28/Wholphin_fork/discussions/new?category=q-a
    about: Please ask questions here
